name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - release-v*
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Choose the Ruby version that suits your project requirements
          bundler-cache: true  # Automatically cache and install gems

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-bundler ruby-dev
          gem install racc -v '1.6.0'

      - name: Install project dependencies
        run: |
          bundle install

      - name: Build site with Jekyll
        run: |
          bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site